version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: bullmq_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass myStrongRedisPass123
    volumes:
      - redis-data:/data

volumes:
  redis-data:
